stages:
  # - build
  - test

unit-test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - dotnet test ./Test/Unit/Unit.csproj

integration-test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - dotnet test ./Test/Integration/Integration.csproj