stages:
  - unit-test
  - integration-test

unit-test:
  stage: unit-test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - dotnet test ./Test/Unit/Unit.csproj

integration-test:
  stage: integration-test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - dotnet test ./Test/Integration/Integration.csproj
  needs: ['unit-test']