name: GitHub Actions Demo
on: [push]
jobs:
    Unit-Test:
        strategy:
            matrix:
                os: [ubuntu-latest]
        # runs-on: ${{ matrix.os }}
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/dotnet/sdk:7.0
        steps:
            - name: Bora buildar
              run: dotnet build
            - name: Vamo pegar o nome
              run: pwd
            - name: E os arquivo
              run: dir .
            - name: Run test
              run: dotnet test ./Test/Unit/Unit.csproj
    Integration-Test:
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        container:
            image: mcr.microsoft.com/dotnet/sdk:7.0
        needs: Unit-Test
        steps:
            - name: Run test
              run: dotnet test ./Test/Integration/Integration.csproj
