name: Twitter API Workflow
on:
  # workflow-dispatch:

  push:
    branches: [main]
  pull_request:


jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - name: "Unit test cases"
        run: dotnet test ./Test/Unit/Unit.csproj
  # integration-test:
  #   script:
  #     - dotnet test ./Test/Integration/Integration.csproj

# unit-test:
#   stage: test
#   image: mcr.microsoft.com/dotnet/sdk:7.0

# integration-test:
#   stage: test
#   image: mcr.microsoft.com/dotnet/sdk:7.0

#   needs: ['unit-test']